name: register

on:
  schedule:
    # github actions のデフォルトの time zone が UTC なので、日本時間 - 9時間 した値を書く
    - cron: "30 21 * * *"
  workflow_dispatch:

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: echo 'CHROMEAPP=google-chrome' >> $GITHUB_ENV
      - run: |
          CHROME_VERSION=$("$CHROMEAPP" --version | cut -f 3 -d ' ' | cut -d '.' -f 1)
          echo "CHROMEDRIVER_VERSION=$(curl --location --fail --retry 10 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})" >> $GITHUB_ENV

      - uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: ${{ env.CHROMEDRIVER_VERSION }}
      - name: Install driver
        run: |
          sudo pip3 install selenium
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # disable headless mode
          python3 $GITHUB_WORKSPACE/__tests__/chromedriver.py

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.2

      - name: install dependencies
        run: poetry install

      - name: Run main
        run: poetry run python src/main.py
        env:
          COMPANYEMAIL: ${{ secrets.COMPANYEMAIL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
